version: "3.6"

services:
  auth-server:
    restart: always
    container_name: ${CONTAINER_NAME}
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_VERSION}
    ports:
      - ${CONTAINER_PORT}:8050
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_CONF_EXT}:${VOLUME_CONF_INN}:ro
    command: [./ubiquitous-auth-server, $ENV_PATH]

    # only for debugging
    # tty: true

networks:
  default:
    external:
      name: prod
