FROM rustlang/rust:nightly-slim AS builder

RUN update-ca-certificates

# Create appuser
ENV USER=docker
ENV UID=10001

# RUN adduser \
#     --disabled-password \
#     --gecos "" \
#     --home "/nonexistent" \
#     --shell "/sbin/nologin" \
#     --no-create-home \
#     --uid "${UID}" \
#     "${USER}"