version: '3.6'

services:
  api-gateway:
    restart: always
    container_name: ${CONTAINER_NAME}
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_VERSION}
    ports:
      - ${CONTAINER_PORT}:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_CONF_EXT}:${VOLUME_CONF_INN}:ro
    command: ./ubiquitous-api-gateway -c ${LURA_PATH}

networks:
  default:
    external: 
      name: prod

