version: "3.6"

services:
  asset-management:
    restart: always
    image: ${AM_BASE_NAME}:${AM_BASE_VERSION}
    container_name: ${AM_API_CONTAINER_NAME}
    ports:
      - ${AM_API_CONTAINER_PORT}:${AM_API_CONTAINER_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # temporary not needed
      # - ${VOLUME_CONF_EXT}:${VOLUME_CONF_INN}:ro
      - ${VOLUME_LOG_EXT}:${VOLUME_LOG_INN}:ro
    command: java -jar app.jar
    # tty: true

networks:
  default:
    external:
      name: prod
